contact_map/__init__.py
contact_map/contact_map.py
contact_map/min_dist.py
contact_map/tests/test_contact_map.py
contact_map/tests/trajectory.pdb

This will include tests for the main contact-related objects. And I'm moving over to `pytest`!

Basic test suite for contacts

---

ci/conda-recipe/meta.yaml
setup.py

The 0.1.x release cycle is primarily for testing automated release process we're putting in place. The first release for public use will be 0.2.0. This is a test release for 0.2.0.
This release fixes a bug in the deployment process from the previous release. See the [release notes for 0.1.3](https://github.com/dwhswenson/contact_map/releases/tag/v0.1.3) for more information about new features and other improvements.

Release 0.1.4

---

ci/conda-recipe/meta.yaml
setup.py

The 0.1.x release cycle is primarily for testing automated release process we're putting in place. The first release for public use will be 0.2.0. This is a test release for 0.2.0.
This release fixes a bug in the deployment process from the previous release. See the [release notes for 0.1.3](https://github.com/dwhswenson/contact_map/releases/tag/v0.1.3) for more information about new features and other improvements.

Release 0.1.5

---

ci/conda-recipe/meta.yaml
setup.py

First public-ready release of `contact_map`. This marks the version that will be used for the E-CAM module.
Future release notes will details new features and other improvements. API breaks will also be included in the release notes. Following [semver](http://semver.org), during the `0.x.y` cycle, API breaks are allowed (although we will try to only make them between `0.x.y` and `0.(x+1).0`). After 1.0, API breaks will require a change of the major version number.
Some of the details in the progress to date can be seen in the release notes from the experimental releases of the `0.1.x` sequence. More complete documentation is available at https://contact-map.readthedocs.io/

Release 0.2.0

---

contact_map/contact_map.py
contact_map/py_2_3.py
contact_map/tests/test_contact_map.py
contact_map/tests/utils.py
docs/Makefile
docs/api.rst
docs/conf.py

Serializing objects will facilitate task-based parallelization. This provides serialization to Python dicts or to JSON strings.
NOTE: One limitation (as of the current implementation) is that subclasses (or duck-punched versions) of contact objects cannot be stored as the components of a `ContactDifference`. In the future, I may try to allow subclasses, but you can't count on duck-typing to work.

Contact Object Serialization

---

contact_map/__init__.py
contact_map/contact_map.py
contact_map/dask_runner.py
contact_map/frequency_task.py
contact_map/tests/test_contact_map.py
contact_map/tests/test_dask_runner.py
contact_map/tests/test_frequency_task.py
docs/api.rst
examples/dask_contact_frequency.ipynb
optional_installs.txt

This uses dask.distributed to parallelize the `ContactFrequency` calculation.

Parallelization of ContactFrequency with Dask.distributed

---

contact_map/contact_map.py
contact_map/dask_runner.py
contact_map/tests/test_contact_map.py
contact_map/tests/test_dask_runner.py
contact_map/tests/test_frequency_task.py
contact_map/tests/utils.py

A little code housekeeping. Removing unused imports, unused vars, etc.

Pylint/Codacy clean-up

---

.travis.yml

`pandas` no longer has wheels for Py-3.4, so we can't pip-install. We require pandas for serialization/deserialization, which is an essential (not optional) feature. Therefore we can no longer support 3.4. Also, MDTraj doesn't test against 3.4 anyway.

Drop Python 3.4 support [travis]

---

contact_map/tests/test_contact_count.py

Since pandas version `0.23` a `FutureWarning` popped up:
```
contact_map/tests/test_contact_count.py::TestContactCount::()::test_df
/home/sander/github_files/contact_map/contact_map/tests/test_contact_count.py:74: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
assert_array_equal(atom_df.to_dense().as_matrix(),
/home/sander/github_files/contact_map/contact_map/tests/test_contact_count.py:76: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
assert_array_equal(residue_df.to_dense().as_matrix(),
```
This fixes that warning in the way proposed by the warning

fixed pandas future warn about as_matrix

---

contact_map/tests/test_dask_runner.py

this will try to fix the timeout error on travis, first try is to set the timeout in the client

fix dask travis error

---

contact_map/tests/test_dask_runner.py

We're still occasionally getting an error when dask fails to start up a cluster (not as often as before #40, but still happens sometimes).
This PR changes the `distributed.LocalCluster` startup so that we can retry a fixed number of times. For now, I'm doing 3 retries. In addition, if all the retries fail, this gives a skip instead of a fail.
If all the retries fail in both the Travis jobs where we try dask, then we'll see a drop in coverage, but I think this will also mean that our coverage will be more stable.
Importantly, the skip only happens if the setup fails. And if the setup is failing consistently (e.g., due to an [unlikely!] API change in dask), I hope we'll notice the drop in coverage.

Handle dask TimeoutError exception in tests

---

.travis.yml

Travis is currently installing old versions of pytest with a newer version of pytest-cov, causing errors in tests. This PR is intended to fix that.

Fix problems with pytest

---

contact_map/contact_map.py
contact_map/tests/test_dask_runner.py

Due to an discrepancy between `DaskFrequency` and it's parent class (`ContactMap`) `__init__()`  , we tried to convert indices back to unsliced two times:
*  `DaskFrequency` calls the `super.__init__`:
*  `ContactFrequency.__init__()` converts to sliced indices, calls `_build_contact_map` and converts back to real indices
**However** `DaskFrequency._build_contact_map` constructs new `ContactFrequency` objects and sums them (in unsliced indices), so after this the `ContactFrequency.__init__()` tries to convert these already correct indices back again.
In order to solve this I moved the conversion from sliced to regular indices as part of the `_build_contact_map` routine of `ContactFrequency`.
fixes #51

Fix dask+atom_slice

---

contact_map/contact_map.py
contact_map/plot_utils.py

The colorbar parameters are taken from [here](https://stackoverflow.com/a/26720422) to provide better scaling to square aspect ratio plots (which I also think should be the default aspect ratio)

Fix for lack of unitcell; better colorbar scaling

---

contact_map/tests/test_contact_map.py

This adds an unittest for the failing behavior described by #64 
Fails on current master before that MR was merged, passes on that branch, should pass on the current master
(Also does some minor pep8 fixes)

Added test for non_periodic systems

---

ci/conda-recipe/meta.yaml
requirements.txt
setup.cfg

There's a problem with sparse matrices in pandas 1.0. See #69 for details. Once that gets fixed, we'll unpin.

pin pandas<1.0

---

.travis.yml
appveyor.yml

Currently our Travis script has a Py27/MDTraj dev test job. However, MDTraj has made changes that are incompatible with Py27. We'd already discussed dropping Py27 and Win32 from tests (https://github.com/dwhswenson/contact_map/pull/69#issuecomment-585827472), so I'm doing it now.
While I'm at it, I'm including Py38 in our test matrix (overdue!). Note that the next release will be the last one to guarantee support Python 3.6 (by NEP29 we could already drop 3.6, but I'm going to take a slightly more conservative approach.)

Drop Py27 and Win32; add Py38

---

ci/conda-recipe/meta.yaml
contact_map/contact_count.py
contact_map/tests/test_contact_count.py
requirements.txt
setup.cfg

This gets the tests running under pandas 1.0, but they fail with an assertion error. I think (still need to confirm) that this is the same as https://github.com/pandas-dev/pandas/issues/29814. If so, then it is a bug in pandas.
Maybe release 0.5.0 with a pin to `pandas<1`? It doesn't look like it is easy to generate sparse matrices directly from dict-of-keys in pandas; pandas seems to prefer to take a dense matrix and make it sparse. We don't want to create the dense matrix in the first place.

Fixes for sparse matrix in Pandas 1.0

---

ci/pip-install/testing_requirements.txt
contact_map/contact_count.py
contact_map/py_2_3.py

Coveralls has been (silently) failing since coverage 5 was released (late 2019). This brings coveralls back to our PRs (by switching from the defunct `python-coveralls` to `coveralls`) and excludes from coverage a few things that are no longer expected to be covered by tests (stuff for Python 2 and pandas < 1.1).
The things that are currently excluded should, at some point, be removed. But I see no reason to rush to break things that work for some users -- besides, we haven't officially updated to require these more recent versions; just we don't guarantee that the old versions will continue to work.

Coveralls cleanup

---

ci/conda-recipe/meta.yaml
contact_map/contact_map.py
contact_map/tests/test_contact_map.py
setup.cfg

This is the next step in #82. Removes `ContactMap` and adds `PendingDeprecationWarning` on `ContactFrequency`.
This also bumps the version to 0.7.0.dev0 (which should have been done as soon as we broke the API in #87; changed API means we're developing on the next 0.x).

Remove `ContactMap` (allowing rename `ContactFrequency` => `ContactMap`)

---

environment.yml
postBuild

This will try to setup the right files for binder to be able to run our examples.
This will mainly use:
- `environment.yml` to build the `example` dependencies
- Maybe use a `postBuild` to pull in the example data.
Another PR will actually add the binder links to out repo.
current binder link for this branch:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/sroet/contact_map/try_binder?filepath=%2Fexamples)
Working examples (will update as I go):

Enable binder

---

README.md
docs/conf.py
docs/examples/index.rst

after pr #92 
This PR adds the repective binder links to the 
(@dwhswenson any place missing? for example I can add a link to each `ipynb` that would start binder for themself)

Add binder links

---

docs/conf.py

I looked at the latest release
The good news: It builds the links against the `v0.7.0` tag.
The bad news: I apparently did not check all the links properly enough and the one with spaces (`Comparing different structures`) led to dead links. (Binder reverts to the example directory, but the github link just straight up fails.)
This fixes it by replacing the spaces with `%20` which do work in links.

Fix spaces in links

---

README.md

The reason I thought #99 was not completed yet, was due to this badge still linking to .org. This fixes that

Update Travis badge to .com instead of .org

---

contact_map/contact_count.py
contact_map/contact_map.py

Our test suite currently fails to cover 5 lines. This PR should fix that.
* One line was not covered because the `with_colorbar` option wasn't passed from `ContactCount.plot` to `ContactCount.plot_axes` in #79. This PR adds that functionality back in.
* Four lines were not covered because the implementation at `ContactObject.atom_contacts` and `ContactObject.residue_contacts` are now overridden in all subclasses. It used to be that `ContactMap` used these, but `ContactMap` was removed in #88. This PR makes those explicitly abstract by raising `NotImplementedError`.

Fix lines missing from test coverage

---

contact_map/contact_trajectory.py

while working on #115 , a test started failing with:
```
_______________________________ TestMutableContactTrajectory.test_hash_eq _______________________________
self = <contact_map.tests.test_contact_trajectory.TestMutableContactTrajectory object at 0x7fca5ea18dc0>
def test_hash_eq(self):
cmap = MutableContactTrajectory(self.traj, cutoff=0.075,
n_neighbors_ignored=0)
assert hash(cmap) != hash(self.map)
>       assert cmap != self.map
E       assert <contact_map.contact_trajectory.MutableContactTrajectory object at 0x7fca5ed678b0> != <contact_map.contact_trajectory.MutableContactTrajectory object at 0x7fca5eaa5850>
E        +  where <contact_map.contact_trajectory.MutableContactTrajectory object at 0x7fca5eaa5850> = <contact_map.tests.test_contact_trajectory.TestMutableContactTrajectory …
```

define forgotten ne

---

docs/index.rst

This removes the page at https://contact-map.readthedocs.io/en/latest/genindex.html from the docs. Prior to today, that page had been visited only once this year. It seems to me like it is more likely to confuse users than help them (it only indexes the API sections, and the search functionality/browsing the API docs should be easier to use than this index.)

Remove genindex from docs

---

appveyor.yml
contact_map/tests/test_plot_utils.py

I was looking into the reason why a `UserWarning` surfaced from our test suite.
```
=========================================== warnings summary ============================================
contact_map/tests/test_plot_utils.py::test_is_cmap_diverging[custom]
/home/sander/github_files/contact_map/contact_map/plot_utils.py:31: UserWarning: Unknown colormap: Treating as sequential.
warnings.warn("Unknown colormap: Treating as sequential.")
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```
The reason was that the variable `cmap` was redefined before the line `if cmap == 'custom'` leading to the `if` statement never being true. 
This fixes that, makes sure we raise the correct warning and keeps the warning from showing up in the warning summary)
It also solves some whitespace …

Actually test for the Userwarning on custom cmaps

---

README.md

after #120 we should also drop the corresponding appveyor status badge from the readme

also drop appveyor badge

---

.github/workflows/unit-tests.yml

OPS just got hit by a [planned brownout of the bash uploader](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) of codecov to notify of the planned deprecation. This swaps the usage of the deprecated bash uploader for [v2 of their github action](https://github.com/marketplace/actions/codecov)

swap from codecov bash uploader to their github action

---

contact_map/plot_utils.py

With the release of matplotlib `3.6.0` we triggered an error because we relied on [deprecated behavior](https://github.com/matplotlib/matplotlib/blob/d04c8de4a89ab756a137ef146e8542e81041909f/lib/matplotlib/figure.py#L1182-L1191)
(We did not trigger the deprecation warning as our `mappable` does not have the attribute `axes`)
This reinstates the old behavior (grabbing the current `axes` via `plt.gca()`)

fix matplotlib 3.6 'Unable to determine Axes to steal space for Colorbar

---

contact_map/tests/test_contact_count.py

our test suite started warning:
```
contact_map/tests/test_contact_count.py::TestContactCount::test_pixel_warning
/home/sroet/miniconda3/envs/contact_map/lib/python3.9/site-packages/_pytest/python.py:192: PytestRemovedIn8Warning: Passing None has been deprecated.
See https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests for alternatives in common use cases.
result = testfunction(**testargs)
```
This updates the "no warning" check to the new recommendation in [that link](https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests)

use new way of checking for no warnings

---

contact_map/tests/test_concurrence.py
contact_map/tests/test_contact_count.py
contact_map/tests/test_contact_map.py
contact_map/tests/test_contact_trajectory.py
contact_map/tests/test_dask_runner.py
contact_map/tests/test_frequency_task.py
contact_map/tests/test_min_dist.py
contact_map/tests/test_plot_utils.py

Pytest prefers (and now, apparently requires) the use of `setup_method` instead of `setup`.
Looks like there was also a problem to fix about newer pytest not liking `pytest.warns(None)` as a way to indicate that no warnings were issued.

tests: `setup`,`teardown` -> `setup_method`, etc

---

.github/workflows/unit-tests.yml

Aside from being overdue and needed, this is largely in response to a CI failure due to a change in mdtraj-dev. If this is just that our Python CI is out of date, then the problem is on us. If we're still failing after this PR, then we'll take it upstream.

Update Python versions in CI
